#DO THE TEST EACH 6 HOURS FROM MONDAY TO FRIDAY
name: Cypress tests scheduled
on: 
  schedule:
  - cron: "0 */6 * * 5"
  
  push:
    branches:
     - 'main'
      
  workflow_dispatch:

jobs:

  #test_schedule:
  checkout-and-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: run cypress tests with chrome
        uses: cypress-io/github-action@v2
        timeout-minutes: 10
        with:
          browser: chrome
      - name: Generate report
        run: cd cypress && npm run posttest
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: cypress-cucumber-report
          path: cypress/cucumber-report/
